name: offline_note
description: "Offline note is a Flutter app that showcases the use of the Drift Database, Firebase Firestore & Firebase Storage."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^18.0.1
  firebase_core: ^4.15.0
  cloud_firestore: ^6.10.0
  firebase_storage: ^13.6.0
  image_picker: ^1.2.3
  flutter_image_compress: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets: 
    - images/avataar_ben.png