// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH-8LANxYJO5Go8O-FQKKue5Ijz01PFYs',
    appId: '1:360154002151:web:c48d054ae750f35998a842',
    messagingSenderId: '360154002151',
    projectId: 'offline-note-20253',
    authDomain: 'offline-note-20253.firebaseapp.com',
    storageBucket: 'offline-note-20253.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3L5hW9fFZXxhzYanlqVg4tWTHt0nY7ls',
    appId: '1:360154002151:android:64f45a8f67212dfa98a842',
    messagingSenderId: '360154002151',
    projectId: 'offline-note-20253',
    storageBucket: 'offline-note-20253.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAueo1VWjPhxdoYSwmrAdZ6d5uSDCh_Cmc',
    appId: '1:360154002151:ios:e181f0fd6858a71098a842',
    messagingSenderId: '360154002151',
    projectId: 'offline-note-20253',
    storageBucket: 'offline-note-20253.firebasestorage.app',
    iosBundleId: 'com.example.offlineNote',
  );
}
