// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6AKSo_QtryLrKuLRrNNudcDW1J1BJkEg',
    appId: '1:258856870611:web:cad5419c134513aadf6a26',
    messagingSenderId: '258856870611',
    projectId: 'offline-note-23200',
    authDomain: 'offline-note-23200.firebaseapp.com',
    storageBucket: 'offline-note-23200.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCARFkRszBVMxfvp_SbaT763NuWfSG83rU',
    appId: '1:258856870611:android:39f773def74e782fdf6a26',
    messagingSenderId: '258856870611',
    projectId: 'offline-note-23200',
    storageBucket: 'offline-note-23200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa1aUry0dRC2MpUbPCQCnj08XzTZVIjyY',
    appId: '1:258856870611:ios:c3ed0f2436e5c272df6a26',
    messagingSenderId: '258856870611',
    projectId: 'offline-note-23200',
    storageBucket: 'offline-note-23200.firebasestorage.app',
    iosBundleId: 'com.example.offlineNote',
  );

}